/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/parser.hpp"

#include "roq/hyperliquid/json/instrument_info.hpp"

using namespace roq;
using namespace roq::hyperliquid;

using namespace std::literals;
using namespace std::chrono_literals;

namespace {
// selective
auto const MESSAGE = R"([)"
                     R"({)"
                     R"("universe":[{)"
                     R"("szDecimals":2,)"
                     R"("name":"SOL",)"
                     R"("maxLeverage":10,)"
                     R"("marginTableId":10)"
                     R"(},)"
                     R"({"szDecimals":1,)"
                     R"("name":"MATIC",)"
                     R"("maxLeverage":50,)"
                     R"("marginTableId":50,)"
                     R"("isDelisted":true)"
                     R"(},{)"
                     R"("szDecimals":0,)"
                     R"("name":"WLFI",)"
                     R"("maxLeverage":3,)"
                     R"("marginTableId":3,)"
                     R"("onlyIsolated":true)"
                     R"(})"
                     R"(],)"
                     R"("marginTables":[[)"
                     R"(50,{)"
                     R"("description":"",)"
                     R"("marginTiers":[)"
                     R"({"lowerBound":"0.0","maxLeverage":50})"
                     R"(])"
                     R"(})"
                     R"(],[)"
                     R"(51,{)"
                     R"("description":"test 50x",)"
                     R"("marginTiers":[)"
                     R"({"lowerBound":"0.0","maxLeverage":50},)"
                     R"({"lowerBound":"10000.0","maxLeverage":20},)"
                     R"({"lowerBound":"100000.0","maxLeverage":5})"
                     R"(])"
                     R"(})"
                     R"(],[)"
                     R"(52,{)"
                     R"("description":"tiered 10x",)"
                     R"("marginTiers":[)"
                     R"({"lowerBound":"0.0","maxLeverage":10},)"
                     R"({"lowerBound":"20000.0","maxLeverage":5},)"
                     R"({"lowerBound":"100000.0","maxLeverage":3}])"
                     R"(})"
                     R"(],[)"
                     R"(53,{)"
                     R"("description":"tiered 25x",)"
                     R"("marginTiers":[)"
                     R"({"lowerBound":"0.0","maxLeverage":25},)"
                     R"({"lowerBound":"20000.0","maxLeverage":10},)"
                     R"({"lowerBound":"50000.0","maxLeverage":5},)"
                     R"({"lowerBound":"200000.0","maxLeverage":3})"
                     R"(])"
                     R"(})"
                     R"(],[)"
                     R"(54,{)"
                     R"("description":"tiered 40x",)"
                     R"("marginTiers":[)"
                     R"({"lowerBound":"0.0","maxLeverage":40},)"
                     R"({"lowerBound":"10000.0","maxLeverage":25},)"
                     R"({"lowerBound":"50000.0","maxLeverage":10},)"
                     R"({"lowerBound":"100000.0","maxLeverage":5},)"
                     R"({"lowerBound":"300000.0","maxLeverage":3})"
                     R"(])"
                     R"(})"
                     R"(],[)"
                     R"(55,{)"
                     R"("description":"tiered 10x _2_",)"
                     R"("marginTiers":[)"
                     R"({"lowerBound":"0.0","maxLeverage":10},)"
                     R"({"lowerBound":"10000.0","maxLeverage":5})"
                     R"(])"
                     R"(})"
                     R"(])"
                     R"(])"
                     R"(},[{)"
                     R"("funding":"0.0000125",)"
                     R"("openInterest":"4739.06",)"
                     R"("prevDayPx":"199.25",)"
                     R"("dayNtlVlm":"424006.5287999998",)"
                     R"("premium":"0.0007224738",)"
                     R"("oraclePx":"207.62",)"
                     R"("markPx":"207.76",)"
                     R"("midPx":"207.79",)"
                     R"("impactPxs":["207.77","207.81"],)"
                     R"("dayBaseVlm":"2062.37")"
                     R"(},{)"
                     R"("funding":"0.0000125",)"
                     R"("openInterest":"14487.68",)"
                     R"("prevDayPx":"4.3299",)"
                     R"("dayNtlVlm":"399.085402",)"
                     R"("premium":"-0.0002507694",)"
                     R"("oraclePx":"4.3865",)"
                     R"("markPx":"4.3842",)"
                     R"("midPx":"4.3836",)"
                     R"("impactPxs":["4.3818","4.3854"],)"
                     R"("dayBaseVlm":"91.18")"
                     R"(},{)"
                     R"("funding":"0.0",)"
                     R"("openInterest":"126.0",)"
                     R"("prevDayPx":"0.39791",)"
                     R"("dayNtlVlm":"133.59181",)"
                     R"("premium":null,)"
                     R"("oraclePx":"0.40361",)"
                     R"("markPx":"0.40419",)"
                     R"("midPx":"0.404185",)"
                     R"("impactPxs":null,)"
                     R"("dayBaseVlm":"338.0")"
                     R"(})"
                     R"(])"
                     R"(])";

}  // namespace

TEST_CASE("json_meta_and_asset_contexts", "[json_meta_and_asset_contexts]") {
  /*
  std::vector<std::byte> buffer(8192);
  json::InstrumentInfo obj{MESSAGE, buffer};
  CHECK(obj.ret_code == 0);
  */
}
